# =============================================================================
# File        : compose.yaml
# Author      : yukimemi
# Last Change : 2024/05/01 16:02:09.
# =============================================================================

services:
  influxdb:
    image: influxdb:2.7.8
    container_name: influxdb
    volumes:
      - ./docker/influxdb2/data:/var/lib/influxdb2
      - ./docker/influxdb2/config:/etc/influxdb2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=organization
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket

  grafana:
    image: grafana/grafana-oss:11.1.3
    container_name: grafana
    user: '0'
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SECURITY_ADMIN_PASSWORD=password
